Bug #1066878 bsp: camera: fix Wenum-conversion warnings for clang
[root cause  ] clang build [-Werror,-Wenum-conversion]
[changes     ] use the right type, or explicitly cast
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

camera/core/dcam_if_r5p0_isp_r6p12/src/isp_drv.c:226:26: error: implicit
conversion from
enumeration type 'enum isp_drv_rtn' to different enumeration type 'enum
dcam_drv_rtn' [-Werror,-Wenum-conversion]
enum dcam_drv_rtn rtn = ISP_RTN_SUCCESS;
~~~   ^~~~~~~~~~~~~~~
camera/core/dcam_if_r5p0_isp_r6p12/src/isp_drv.c:2809:11: error:
implicit conversion from
enumeration type 'enum dcam_drv_rtn' to different enumeration type 'enum
isp_drv_rtn' [-Werror,-Wenum-conversion]
rtn = DCAM_RTN_PATH_ADDR_ERR;
~ ^~~~~~~~~~~~~~~~~~~~~~
camera/core/dcam_if_r5p0_isp_r6p12/src/isp_drv.c:2857:11: error:
implicit conversion from
enumeration type 'enum dcam_drv_rtn' to different enumeration type 'enum
isp_drv_rtn' [-Werror,-Wenum-conversion]
rtn = DCAM_RTN_PATH_ADDR_ERR;
~ ^~~~~~~~~~~~~~~~~~~~~~

camera/core/dcam_if_r5p0_isp_r6p12/block/isp_k_ebd.c:38:20: error:
implicit conversion from
enumeration type 'enum isp_id' to different enumeration type 'enum
dcam_id' [-Werror,-Wenum-conversion]
enum dcam_id id = ISP_ID_0;
~~   ^~~~~~~~

camera/core/dcam_if_r5p0_isp_r6p12/block/isp_k_pdaf.c:305:20: error:
implicit conversion from
enumeration type 'enum isp_id' to different enumeration type 'enum
dcam_id' [-Werror,-Wenum-conversion]
enum dcam_id id = ISP_ID_0;
~~   ^~~~~~~~
camera/core/dcam_if_r5p0_isp_r6p12/src/isp_int.c:478:20: error: implicit
conversion from
enumeration type 'enum isp_id' to different enumeration type 'enum
dcam_id' [-Werror,-Wenum-conversion]
enum dcam_id id = ISP_ID_0;
~~   ^~~~~~~~
camera/core/dcam_if_r5p0_isp_r6p12/src/isp_int.c:501:7: error: implicit
conversion from
enumeration type 'enum isp_id' to different enumeration type 'enum
dcam_id' [-Werror,-Wenum-conversion]
id = idx;
~ ^~~

Change-Id: Ibf23108bc1cfa2fb0e926dcbb28790b3976f649f
Signed-off-by: Candle Sun <candle.sun@unisoc.com>
(cherry picked from commit 240cbf8d3bc4410fd33620aaacf3bfee0cf143b5)